FROM node:20-alpine AS build

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

# Очистка кэша npm
RUN npm cache clean --force

RUN chown root.root .

RUN npm install 

COPY . .

ENV NODE_ENV=production

RUN npm run build

