FROM node:20-alpine3.18 AS build

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

# Очистка кэша npm
RUN npm cache clean --force

RUN npm install 

COPY . .

ENV NODE_ENV=production

RUN npm run build

