FROM node:20-alpine AS build

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

# Очистка кэша npm
RUN npm cache clean --force

RUN npm install --legacy-peer-deps

COPY . .

ENV NODE_ENV=production

RUN npm run build

